# Image de départ, build étant le nom de l'image
FROM  node:14-alpine AS build 

WORKDIR /app

COPY package*.json ./ 

RUN npm install 

COPY . .

RUN npm run build

FROM nginx AS deploy

COPY --from=build /app/build /usr/share/nginx/html


EXPOSE 80

CMD ["nginx","-g","daemon off;"]

# et dans le terminal
# docker build --no-cache -t reactapp .
# docker run --name containerreact -p 8085:80 -d reactapp
