FROM maven AS build 

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src 
RUN mvn package -DskipTests 


FROM openjdk AS deploy

WORKDIR /app

COPY --from=build /app/target/common-data-service.jar .

EXPOSE ${COMMON_DATA_SERVICE_PORT}

CMD ["java", "-jar", "common-data-service.jar"]


# et dans le terminal 
# docker build --no-cache -t commondataserv .
# docker run --name containercommondataserv -p 9092:9000 -d commondataserv