version: "3"

services:
  # Database
  bdd:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:${DB_PORT}"  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - network-e-commerce

  # Redis
  redis:
     image: redis:latest
     ports:
       - "${REDIS_PORT}:${REDIS_PORT}"
     command: redis-server --requirepass ${REDIS_PASSWORD}
     networks:
      - network-e-commerce


  # Backend - Authentication Service
  authentication-service:
    container_name: authentication-service
    ports:
      - "${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}"  
    build:
      context: ./server/authentication-service
      dockerfile: Dockerfile
    environment:
      PORT: ${AUTHENTICATION_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_HOST: bdd
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - network-e-commerce


  # Backend - Payment Service
  payment-service:
    container_name: payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"  
    build:
      context: ./server/payment-service
      dockerfile: Dockerfile
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DATABASE}  
      PORT: ${PAYMENT_SERVICE_PORT}
      DB_HOST: bdd
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - network-e-commerce


  # Backend - Common Data Service
  common-data-service:
    container_name: common-data-service
    ports:
      - "${COMMON_DATA_SERVICE_PORT}:${COMMON_DATA_SERVICE_PORT}" 
    build:
      context: ./server/common-data-service
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PORT: ${COMMON_DATA_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_HOST: bdd
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - network-e-commerce

  # Backend - Search Suggestion Service
  # search-suggestion-service:
  #   container_name: search-suggestion-service
  #   ports:
  #     - "${SEARCH_SUGGESTION_SERVICE_PORT}:${SEARCH_SUGGESTION_SERVICE_PORT}"  
  #   build:
  #     context: ./server/search-suggestion-service
  #     dockerfile: Dockerfile
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}  
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: 6379
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     PORT: ${SEARCH_SUGGESTION_SERVICE_PORT}
  #     ACTIVE_PROFILE: ${ACTIVE_PROFILE}
  #     DB_HOST: bdd
  #     DB_PORT: ${DB_PORT}
  #     DB_SCHEMA: ${DB_SCHEMA}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #   networks:
  #     - network-e-commerce


  # Frontend
  react-nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-nginx
    ports:
      - "3000:80"  
    depends_on:
      - authentication-service
    networks:
      - network-e-commerce
    


networks:
  network-e-commerce:
    driver: bridge


volumes:
  db_data:
  redis_data:
