FROM maven AS build 

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src 
RUN mvn package -DskipTests 


FROM openjdk AS deploy

WORKDIR /app

COPY --from=build /app/target/payment-service.jar .

EXPOSE ${AUTHENTICATION_SERVICE_PORT}

CMD ["java", "-jar", "payment-service.jar"]


# et dans le terminal 
# docker build --no-cache -t paymentserv .
# docker run --name containerpaymentserv -p 9093:950 -d paymeentserv