FROM maven AS build 

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src 
RUN mvn clean package -DskipTests 


FROM openjdk AS deploy

WORKDIR /app

COPY --from=build /app/target/payment-service.jar .

EXPOSE ${PAYMENT_SERVICE_PORT}

CMD ["java", "-jar", "payment-service.jar"]



