FROM maven AS build 

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src 
RUN mvn clean package -DskipTests 


FROM openjdk AS deploy

WORKDIR /app

COPY --from=build /app/target/search-suggestion-service.jar .

EXPOSE ${SEARCH_SUGGESTION_SERVICE_PORT}

CMD ["java", "-jar", "search-suggestion-service.jar"]



